{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simpwatch.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "simpwatch.labels" . | nindent 4 }}
{{- end }}
