apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simpwatch-db-data
  namespace: simpwatch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-nas
