# Generated by Django 6.0.5 on 2026-05-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpwatch', '0005_twitchbroadcastergrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchBotGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_username', models.CharField(max_length=255, unique=True)),
                ('bot_user_id', models.CharField(max_length=255, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('scopes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='twitchbroadcastergrant',
            new_name='simpwatch_t_is_acti_f405ff_idx',
            old_name='simpwatch_t_is_acti_ee8f3d_idx',
        ),
        migrations.AddIndex(
            model_name='twitchbotgrant',
            index=models.Index(fields=['is_active'], name='simpwatch_t_is_acti_eb2c9b_idx'),
        ),
    ]
