# Generated by Django 6.0.5 on 2026-07-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simpwatch", "0011_repair_missing_scoreadjustment_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoreadjustment",
            name="adjustment_type",
            field=models.CharField(
                choices=[
                    ("simp", "Simp"),
                    ("bamder", "Bamder"),
                    ("banthem", "Banthem"),
                    ("criminal", "Criminal"),
                    ("death", "Death"),
                ],
                default="simp",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="simpevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("simp", "Simp"),
                    ("bamder", "Bamder"),
                    ("banthem", "Banthem"),
                    ("criminal", "Criminal"),
                    ("death", "Death"),
                ],
                default="simp",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TwitchChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=255, unique=True)),
                ("is_monitored", models.BooleanField(default=True)),
                ("send_replies", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_monitored", "send_replies"],
                        name="simpwatch_t_is_moni_f24382_idx",
                    )
                ],
            },
        ),
    ]
