# Generated by Django 6.0.5 on 2026-07-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simpwatch", "0012_add_twitch_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitchchannel",
            name="send_replies",
            field=models.BooleanField(default=True),
        ),
    ]
